# Setup
title:               Security Operations Center - Relative Security
tagline:             'Relative Security'
description:         'A home for all the security experiments.'
url:                 
baseurl:             '/mssp-soc'
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Bilal Ahmad
  url:               http://mysticwayfarer7.github.io/mssp-soc/
  email:             mysticwayfarer7@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
