# Setup
title:               Security Operations Center - Mysticwayfarer
tagline:             'Relative Security'
description:         'A home for all the security experiments.  Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 
baseurl:             '/mssp-soc'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Bilal Ahmad
  url:               https://twitter.com/mdo
  email:             mysticwayfarer7@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
